/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.AddCreditUserStatus;
import io.swagger.client.model.ReportQuotaUsageStatus;
import io.swagger.client.model.UserObject;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ChargingdemoprocsApi
 */
@Ignore
public class ChargingdemoprocsApiTest {

    private final ChargingdemoprocsApi api = new ChargingdemoprocsApi();

    /**
     * Adds Credit
     *
     * Adds Credit
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void addCreditTest() throws Exception {
        Long userId = null;
        Long extraCredit = null;
        String txnId = null;
        AddCreditUserStatus response = api.addCredit(userId, extraCredit, txnId);

        // TODO: test validations
    }
    /**
     * Delete User
     *
     * Delete User
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void delUserTest() throws Exception {
        Long userId = null;
        String response = api.delUser(userId);

        // TODO: test validations
    }
    /**
     * GetAndLockUser
     *
     * GetAndLockUser
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAndLockUserTest() throws Exception {
        Long body = null;
        UserObject response = api.getAndLockUser(body);

        // TODO: test validations
    }
    /**
     * GetUser
     *
     * GetUser
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUserTest() throws Exception {
        Long userId = null;
        UserObject response = api.getUser(userId);

        // TODO: test validations
    }
    /**
     * Spends Credit
     *
     * Spends Credit
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void reportQuotaUsageTest() throws Exception {
        Long userId = null;
        Integer unitsUsed = null;
        Integer unitsWanted = null;
        Long inputSessionId = null;
        String txnId = null;
        ReportQuotaUsageStatus response = api.reportQuotaUsage(userId, unitsUsed, unitsWanted, inputSessionId, txnId);

        // TODO: test validations
    }
    /**
     * UpdateLockedUser
     *
     * UpdateLockedUser
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateLockedUserTest() throws Exception {
        Long userId = null;
        Long sessionId = null;
        String jsonPayload = null;
        String deltaOperationName = null;
        String response = api.updateLockedUser(userId, sessionId, jsonPayload, deltaOperationName);

        // TODO: test validations
    }
    /**
     * UpsertUser
     *
     * UpsertUser
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void upsertUserTest() throws Exception {
        Long body = null;
        String response = api.upsertUser(body);

        // TODO: test validations
    }
}
